# Generated by Django 4.2.4 on 2024-12-04 03:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tourApi", "0009_webinfo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebInfo",
        ),
        migrations.RemoveField(
            model_name="sitemain",
            name="address",
        ),
        migrations.RemoveField(
            model_name="sitemain",
            name="email",
        ),
        migrations.RemoveField(
            model_name="sitemain",
            name="qrcode",
        ),
        migrations.RemoveField(
            model_name="sitemain",
            name="tel",
        ),
    ]
