# Generated by Django 4.2.4 on 2024-12-04 04:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tourApi", "0011_alter_imagebannermodel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagebannermodel",
            options={"verbose_name_plural": "1.1. image banner list"},
        ),
        migrations.AlterModelTable(
            name="imagebannermodel",
            table="ImagebannerModel",
        ),
    ]
